services:
  react:
    image: nginx:latest
    container_name: react-container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
      - ./path/to/your/dist:/var/www/dist        
    ports:
      - "80:80"
    networks:
      - tic-tac-toe

networks:
  tic-tac-toe:
    driver: bridge