services:
  react:
    container_name: react-container
    image: nginx:latest
    volumes:
      - /root/tic-tac-toe/nginx/nginx.conf:/etc/nginx/sites-enabled/default:ro 
    ports:
      - "80:80"
    networks:
      - your-network

networks:
  your-network:
    driver: bridge