services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app/dist:/var/www/dist  лы
      - ./app/.nginx/nginx.conf:/etc/nginx/nginx.conf  
    container_name: react-container
    restart: always